package com.nikola.jakshic.dagger.model.match

import com.google.gson.annotations.Expose
import com.google.gson.annotations.SerializedName

data class PlayerStats(
        @Expose @SerializedName("account_id") var id: Long = 0,
        @SerializedName("name") @Expose var name: String? = null,
        @Expose @SerializedName("personaname") var personaName: String? = null,
        @Expose @SerializedName("avatarfull") var avatarUrl: String? = null,
        @Expose @SerializedName("win") var wins: Long = 0,
        @Expose @SerializedName("lose") var losses: Long = 0,
        var expanded: Boolean = false,

        @SerializedName("player_slot") @Expose var playerSlot: Long = 0,
        @SerializedName("assists") @Expose var assists: Long = 0,
        @SerializedName("backpack_0") @Expose var backpack0: Long = 0,
        @SerializedName("backpack_1") @Expose var backpack1: Long = 0,
        @SerializedName("backpack_2") @Expose var backpack2: Long = 0,
        @SerializedName("camps_stacked") @Expose var campsStacked: Long = 0,
        @SerializedName("creeps_stacked") @Expose var creepsStacked: Long = 0,
        @SerializedName("deaths") @Expose var deaths: Long = 0,
        @SerializedName("denies") @Expose var denies: Long = 0,
        @SerializedName("gold_per_min") @Expose var goldPerMin: Long = 0,
        @SerializedName("gold_reasons") @Expose var goldReasons: GoldReasons? = null,
        @SerializedName("gold_t") @Expose var goldT: List<Long>? = null,
        @SerializedName("dn_t") @Expose var dnT: List<Long>? = null,
        @SerializedName("hero_damage") @Expose var heroDamage: Long = 0,
        @SerializedName("hero_healing") @Expose var heroHealing: Long = 0,
        @SerializedName("hero_id") @Expose var heroId: Long = 0,
        @SerializedName("item_0") @Expose var item0: Long = 0,
        @SerializedName("item_1") @Expose var item1: Long = 0,
        @SerializedName("item_2") @Expose var item2: Long = 0,
        @SerializedName("item_3") @Expose var item3: Long = 0,
        @SerializedName("item_4") @Expose var item4: Long = 0,
        @SerializedName("item_5") @Expose var item5: Long = 0,
        @SerializedName("kills") @Expose var kills: Long = 0,
        @SerializedName("last_hits") @Expose var lastHits: Long = 0,
        @SerializedName("level") @Expose var level: Long = 0,
        @SerializedName("lh_t") @Expose var lhT: List<Long>? = null,
        @SerializedName("stuns") @Expose var stuns: Double = 0.toDouble(),
        @SerializedName("tower_damage") @Expose var towerDamage: Long = 0,
        @SerializedName("xp_per_min") @Expose var xpPerMin: Long = 0,
        @SerializedName("xp_reasons") @Expose var xpReasons: XpReasons? = null,
        @SerializedName("xp_t") @Expose var xpT: List<Long>? = null,
        @SerializedName("radiant_win") @Expose var radiantWin: Boolean = false,
        @SerializedName("start_time") @Expose var startTime: Long = 0,
        @SerializedName("duration") @Expose var duration: Long = 0,
        @SerializedName("isRadiant") @Expose var isRadiant: Boolean = false,
        @SerializedName("total_gold") @Expose var totalGold: Long = 0,
        @SerializedName("total_xp") @Expose var totalXp: Long = 0,
        @SerializedName("kills_per_min") @Expose var killsPerMin: Double = 0.toDouble(),
        @SerializedName("purchase_ward_observer") @Expose var purchaseWardObserver: Long = 0,
        @SerializedName("purchase_ward_sentry") @Expose var purchaseWardSentry: Long = 0,
        @SerializedName("purchase_tpscroll") @Expose var purchaseTpscroll: Long = 0,
        @SerializedName("purchase_gem") @Expose var purchaseGem: Long = 0,
        @SerializedName("benchmarks") @Expose var benchmarks: Benchmarks? = null
)